---
- hosts: all
  become: true
  tasks:
  - name: Delete Script if Present
    ansible.builtin.file:
      path: /tmp/cleanLinuxLogs.sh
      state: absent
      
  - name: Download Script from Repository
    get_url: 
      url: https://raw.githubusercontent.com/chaharsanjeev/homeLabAnsibleScripts/main/cleanLinuxLogs.sh 
      dest: /tmp/cleanLinuxLogs.sh

  - name: Change Script Permission For Execute
    ansible.builtin.file:
      path: /tmp/cleanLinuxLogs.sh
      mode: '7777'
    
  - name: Execute Clean Logs Script
    shell: /tmp/cleanLinuxLogs.sh

  - name: Delete Clean Logs Script
    file: 
      path: /tmp/cleanLinuxLogs.sh 
      state: absent
  
  - name: Update all Installed Packages
    apt:
      name: '*'
      state: latest
      update_cache: yes
      only_upgrade: yes
    register: apt_update_status

  - name: Remove Packages Not Needed
    apt:
      autoremove: yes
      autoclean: yes

  - name: Check If Reboot Required
    stat:
      path: /var/run/reboot-required
    register: reboot_required_file

  - name: Sending an e-mail using Gmail SMTP servers
    community.general.mail:
      host: "{{smtp_host}}"
      port: 587
      username: "{{smtp_username}}"
      password: "{{smtp_app_password}}"
      to: "{{alert_emailAddress}}"
      subject: Testing Email from Ansible
      body: System {{ ansible_hostname }} has been successfully send email
    delegate_to: localhost
    when: reboot_required_file.stat.exists == true


  
  #- name: Reboot when packages were updated
  #  reboot:
  #    post_reboot_delay: 60
  #  when: apt_update_status.changed

