---
- hosts: all
  tasks:
- name: Download clean Logs Script
  get_url: 
    url: https://raw.githubusercontent.com/chaharsanjeev/homeLabAnsibleScripts/main/cleanLinuxLogs.sh
    
- name: Download clean Logs Script
  shell: /tmp/cleanLinuxLogs.sh

- name: Delete clean Logs Script
  file: 
    path: /tmp/cleanLinuxLogs.sh 
    state: absent
  
  - name: Update all installed packages using APT module
    apt:
      name: '*'
      state: latest
      update_cache: yes
      only_upgrade: yes
    register: apt_update_status

  - name: Remove packages not needed anymore
    apt:
      autoremove: yes
      autoclean: yes

  - name: Reboot when packages were updated
    reboot:
      post_reboot_delay: 60
    when: apt_update_status.changed

