---
- hosts: host
  become: false
  gather_facts: false
  connection: local

  tasks:
    - name: Pinging Host Machine
      action: ping
      ignore_errors: true
      register: var_ping
    - debug: msg="{var_ping.stdout}"
    - name: save the Json data to a Variable as a Fact
      set_fact:
        jsondata: "{{ var_ping.stdout | from_json }}"

      
