---
- hosts: localhost
  become: false
  gather_facts: false
  tasks:
  - name: Ping Host Machine
    delegate_to: localhost
    shell: "ping -4 {{ ansible_hostname }} "
    register: out
    ignore_errors: yes

  - meta: clear_host_errors

  - name: Ping Response Standard Output
    debug:
      msg: "{{ out.stdout_lines }}"

  - name: Ping Response Return Code 
    debug:
      msg: "{{ out.rc }}"

  - name: Host Machine Ping Failed 
    debug:
      msg: "{{ inventory_hostname }} has 100% packet loss"
    when: "out.stdout_lines is search ('100% packet loss')"
    
  - name: Sending an e-mail using Gmail SMTP servers - Host Machine Not Reachable
    community.general.mail:
      sender: "HomeRack"
      host: "{{smtp_host}}"
      port: 587
      username: "{{smtp_username}}"
      password: "{{smtp_app_password}}"
      to: "{{alert_emailAddress}}"
      subject: HomeRack Machine Down - {{ ansible_hostname }}
      body: Homerack Machine Down - {{ ansible_hostname }}
    delegate_to: localhost
    when: "out.stdout_lines is search ('100% packet loss')"
