---
- hosts: host
  become: false
  gather_facts: false
  connection: local

  tasks:
    - name: Pinging Host Machine
      action: ping
      ignore_errors: true
      register: var_ping
    - debug: msg="{var_ping.stdout}"
      
