version: "3.9"
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - /opt/jellyfin/config:/config
      - /opt/jellyfin/cache:/cache
      - /NAS_Videos:/media
    ports:
      - "8096:8096" # HTTP Web UI
      - "8920:8920" # HTTPS Web UI
    devices:
      - /dev/dri:/dev/dri # For hardware transcoding
    restart: unless-stopped
