version: "3.9"
services:
  frigate:
    container_name: nvr-frigate
    privileged: true
    restart: unless-stopped
    #image: ghcr.io/blakeblackshear/frigate:stable
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    
    # Release URL https://github.com/blakeblackshear/frigate/releases
    #image: ghcr.io/blakeblackshear/frigate:0.14.0-rc2-tensorrt
    #image: ghcr.io/blakeblackshear/frigate:0.14.1-tensorrt
    #image: ghcr.io/blakeblackshear/frigate:0.15.0-beta3-tensorrt

    runtime: nvidia  # Add this line for NVIDIA GPU runtime support

    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          #device_ids: ['0'] # this is only needed when using multiple GPUs
    #          #count: 1 # number of GPUs
    #          count: all
    #          capabilities: [gpu]    
    shm_size: "512mb" # update for your cameras based on the calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
      #- /dev/dri/card0:/dev/dri/card0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config:rw # Used to store the Frigate config file and sqlite database. You will also see a few files alongside the database file while Frigate is running.
      - /NVR_Storage_20TB:/media/frigate:rw
      - /opt/ffmpeg-nvidia/ffmpeg-nvidia-binaries/bin:/usr/local/bin:ro

      #- /mnt/pve/NVR_Storage_20TB:/media/frigate:rw

      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "Tuhina0404"
      FRIGATE_AMCREST_USERNAME: "frigate"
      FRIGATE_AMCREST_PASSWORD: "frigate0404"
      FRIGATE_MQTT_USERNAME: "mqtt_user"
      FRIGATE_MQTT_PASSWORD: "Tuhina@0404"
      PLUS_API_KEY: "de53cb94-a7d1-49c3-9d2e-647f6d4a5381:2f6880ead11f32bc37f2ab46f963cb3fc023beca"
      ONNX_THREAD_COUNT: "1"
      ONNX_DISABLE_AFFINITY: "1"
