---
- hosts: all
  become: true
  tasks:
  - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
  - name: Update Cloudflare DDNS for gateway.sanjeevchahar.com
    community.general.cloudflare_dns:
      account_api_key: "{{cloudflare_account_api_key}}"
      account_email: "{{cloudflare_account_email}}"
      api_token: "{{cloudflare_api_token}}"
      zone: sanjeevchahar.com
      record: gateway.sanjeevchahar.com
      type: A
      value: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}"
    register: record
  
