---
- hosts: all
  become: true
  tasks:
  - name: Update Secondary DNS Server(Raspberry Pi - dns-s.sc) with Primary DNS Server(Proxmox - dns.sc)
    register: reg_gravity_pull
    ignore_errors: True
    retries: 3
    delay: 3
    shell: /bin/bash -c "gravity-sync push" -s 103 111 >>/var/log/gravity-pull.log 2>/dev/null
    args:
      executable: /bin/bash
    environment:
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"


  - name: Send Notify to Telegram - Gravity Push Failed
    when: reg_gravity_pull is failed
    ignore_errors: False
    retries: 3
    delay: 3
    delegate_to: localhost
    community.general.telegram:
      token: "{{telegraph_token}}"
      api_args:
        chat_id: "{{telegraph_chatid}}"
        parse_mode: "plain"
        text: "From Job Server(monitor.sc) \n\nImpacted Host: {{ansible_hostname}}\n\nError Gravity-Sync push from dns.sc to dns-s.sc Server\n\n{{reg_gravity_pull}}"
        disable_web_page_preview: True
        disable_notification: False

  - name: Fail Job - Gravity Push Failed
    when: reg_gravity_pull is failed
    ansible.builtin.fail:
      msg: "Impacted Host: {{ansible_hostname}}\n\nError Deleting Script\n\n{{reg_gravity_pull}}"
