---
- hosts: all
  become: true
  tasks:
  - name: Stop Docker for Proxmox Container - Frigate/NVR
    ansible.builtin.systemd_service:
      name: docker
      state: stopped
  - name: Reboot Proxmox Container - Frigate/NVR
    ansible.builtin.reboot:
      msg: "Reboot initiated by Ansible Patch Server - Scheduled Daily Reboot"
      reboot_timeout: 3600
    delegate_to: nvr.sc
  
