---
- hosts: all
  become: true
  tasks:
  - name: Update pi-hole package
    ignore_errors: false
    retries: 3
    delay: 3
    shell: /bin/bash -c "pihole -up" -s 103 111 >>/var/log/gravity-pull.log 2>/dev/null
    args:
      executable: /bin/bash
    environment:
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
