---
- name: Update and Cleanup Raspberry Pi Apps
  hosts: raspberrypi  # This should be defined in your inventory
  become: yes  # Use sudo to run commands as root
  tasks:

    - name: Update the package list
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes

    - name: Ensure specific app (example: python3) is up to date
      apt:
        name: python3
        state: latest  # Ensure it's up to date
      when: ansible_facts.packages['python3'] is defined

    - name: Ensure specific app (example: nginx) is up to date
      apt:
        name: nginx
        state: latest
      when: ansible_facts.packages['nginx'] is defined

    - name: Remove unused packages
      apt:
        name: "{{ item }}"
        state: absent
      loop:
        - python2
        - unused-package-1  # Replace with actual unused packages if needed
        - unused-package-2
      ignore_errors: yes

    - name: Clear apt cache to free up space
      command: apt-get clean

    - name: Remove old kernel versions
      command: apt-get autoremove --purge -y
      ignore_errors: yes

    - name: Reboot Raspberry Pi if needed
      reboot:
        reboot_timeout: 300
        test_command: whoami
      when: ansible_facts.packages['nginx'] is changed or ansible_facts.packages['python3'] is changed
